### ISSUE TITLE
Entity Renderer Server Crash

### ISSUE THREAD

**Issue by WenXin20** [Kinomora/SlimeGolem#1]
`Minecraft v1.15.2`
`Forge v31.2.45`
`Slime Golem v0.2`

Loading the mod on a server causes it to crash. The previous version worked fine.
[Crash Report](https://gist.github.com/WenXin20/91785171d41efb269909b107d3f40555)

**Comment by Kinomora** [comment]
Thank you, I'll look into fixing it and post a fix when I can :)

**Comment by WenXin20** [comment]
Thanks!

**Comment by Kinomora** [comment]
Crash has been fixed, see release 1.15.2_03!

**Comment by WenXin20** [comment]
Thanks! I tried to run the file marked as 1.16.4, but minecraft says that it is for 1.15.2 only

**Comment by Quarris** [comment]
@Kinomora first stop assigning issues to me. Its your fucking mod. You need to updaye the mods.toml file in resources/METAINF so that the forge and minecraft version in the [[dependencies]] section at the bottom matches. Look at other mods for examples

**Comment by Kinomora** [comment]
Alright, the error is fixed but the textures are bugged so I'm going to fix that what I'm at it and upload the change hopefully tonight
